[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 2

# decorations = "None"

opacity = 0.85
# blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12

[keyboard]
bindings = [
  # Disable < Ctrl + >
  { key = "Equals", mods = "Control", action = "None" },

  # Disable < Ctrl - >
  { key = "Minus", mods = "Control", action = "None" },
]

